In [2]:
import numpy as np

# Define the masks
horizontal_mask = np.array([[-1, -1, -1], [2, 2, 2], [-1, -1, -1]])
plus45_mask = np.array([[-1, -1, 2], [-1, 2, -1], [2, -1, -1]])
vertical_mask = np.array([[-1, 2, -1], [-1, 2, -1], [-1, 2, -1]])
minus45_mask = np.array([[2, -1, -1], [-1, 2, -1], [-1, -1, 2]])

# Define the image
image_a = np.array([[9, 3, 4], [1, 10, 2], [0, 2, 8]])

# Function to perform convolution
def apply_mask(image, mask):
    return np.sum(image * mask)

# Apply each mask to the image
result_horizontal = apply_mask(image_a, horizontal_mask)
result_plus45 = apply_mask(image_a, plus45_mask)
result_vertical = apply_mask(image_a, vertical_mask)
result_minus45 = apply_mask(image_a, minus45_mask)

# Output the results
print("Result of Horizontal Mask:", result_horizontal)
print("Result of +45° Mask:", result_plus45)
print("Result of Vertical Mask:", result_vertical)
print("Result of -45° Mask:", result_minus45)


Result of Horizontal Mask: 0
Result of +45° Mask: 3
Result of Vertical Mask: 6
Result of -45° Mask: 42


In [5]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve2d
from matplotlib import cm

# Define the image
image_a = np.array([[9, 3, 4], 
                    [1, 10, 2], 
                    [0, 2, 8]])

# Define the mask

horizontal_mask = np.array([[-1, -1, -1], 
                            [2, 2, 2], 
                            [-1, -1, -1]])

plus45_mask = np.array([[-1, -1, 2], 
                        [-1, 2, -1], 
                        [2, -1, -1]])

vertical_mask = np.array([[-1, 2, -1], 
                          [-1, 2, -1], 
                          [-1, 2, -1]])

minus45_mask = np.array([[2, -1, -1], 
                         [-1, 2, -1], 
                         [-1, -1, 2]])

# Apply 2D convolution (same padding)
tmphorizontal = convolve2d(image_a, horizontal_mask, mode='same')
tmphorizontal

tmpplus45 = convolve2d(image_a, plus45_mask, mode='same')
tmpplus45

tmpvertical = convolve2d(image_a, vertical_mask, mode='same')
tmpvertical

tmpminus45 = convolve2d(image_a, minus45_mask, mode='same')
tmpminus45


array([[ 34, -14,  -7],
       [-16,  42, -14],
       [-13, -14,  32]])

In [10]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve2d

# Define the image
image_a = np.array([[9, 3, 4], 
                    [1, 10, 2], 
                    [0, 2, 8]])

image_b = np.array([[2, 1, 9], 
                    [0, 7, 3], 
                    [6, 0, 1]])

# Define the masks
horizontal_mask = np.array([[-1, -1, -1], 
                            [2, 2, 2], 
                            [-1, -1, -1]])

plus45_mask = np.array([[-1, -1, 2], 
                        [-1, 2, -1], 
                        [2, -1, -1]])

vertical_mask = np.array([[-1, 2, -1], 
                          [-1, 2, -1], 
                          [-1, 2, -1]])

minus45_mask = np.array([[2, -1, -1], 
                         [-1, 2, -1], 
                         [-1, -1, 2]])

# Apply 2D convolution (same padding)
tmphorizontal = convolve2d(image_b, horizontal_mask, mode='same')
tmpplus45 = convolve2d(image_b, plus45_mask, mode='same')
tmpvertical = convolve2d(image_b, vertical_mask, mode='same')
tmpminus45 = convolve2d(image_b, minus45_mask, mode='same')

# Naming the results
horizontal_result = tmphorizontal
plus45_result = tmpplus45
vertical_result = tmpvertical
minus45_result = tmpminus45

# Print all results
print("Horizontal Mask Result:\n", horizontal_result)
print("\n45-Degree Mask Result:\n", plus45_result)
print("\nVertical Mask Result:\n", vertical_result)
print("\nNegative 45-Degree Mask Result:\n", minus45_result)


Horizontal Mask Result:
 [[-1 14 10]
 [ 5  1  9]
 [ 5  4 -8]]

45-Degree Mask Result:
 [[ -4 -19  28]
 [-13  37 -12]
 [ 26  -8  -8]]

Vertical Mask Result:
 [[-4  2 16]
 [ 8 -5 18]
 [ 5  4  1]]

Negative 45-Degree Mask Result:
 [[ 17 -10   7]
 [-16   1  -9]
 [  5 -17  13]]


In [8]:
18+6+(-1)+(-10)

13